import { createContext, useContext, useState, useEffect } from 'react';

const T = {
    fr: {
        nav: {
            accueil:     'Accueil',
            artiste:     "L'Artiste",
            oeuvres:     'Galerie',
            expositions: 'Expositions',
            presse:      'Presse',
            ateliers:    'Ateliers',
            blog:        'Blogs',
            contact:     'Contact',
        },
        footer: {
            tagline:      "Peintre tunisien entre la tradition et la modernité. Huile, acrylique et pastel au service de l'émotion.",
            navigation:   'Navigation',
            contact:      'Contact',
            sendMessage:  'Envoyer un message',
            joinWorkshop: 'Rejoindre un atelier',
            rights:       'Tous droits réservés.',
            crafted:      'Site réalisé avec soin',
            painter:      'Peintre tunisien',
        },
        bottomNav: {
            accueil:  'Accueil',
            galerie:  'Galerie',
            ateliers: 'Ateliers',
            contact:  'Contact',
        },
        accueil: {
            heroSub:        "Peintre tunisien · fondateur de la peinture de l'absurde",
            statYears:      "Ans d'expérience",
            statWorks:      'Œuvres créées',
            statExpo:       'Expositions',
            portfolioTag:   'Portfolio',
            portfolioTitle: 'Œuvres récentes',
            portfolioCta:   'Voir tout',
            portfolioMobile:'Voir toutes les œuvres',
            clubTag:        'Club & Transmission',
            clubTitle:      'Nos ateliers en images',
            clubCta:        'Rejoindre',
            quoteText:      "La peinture est le silence du monde rendu visible, une confession sans mots, une vérité sans masque.",
            quoteCta:       "Découvrir l'artiste",
        },
        artiste: {
            subnavBio:      'Biographie',
            subnavDemarche: 'Démarche',
            bioTag:         "L'Artiste",
            statLabel1:     'Tunisie',
            statLabel2:     "Années d'art",
            statLabel3:     'Casquettes',
            profLabel:      'Profession',
            profValue:      'Artiste · Professeur · Mentor',
            lieuLabel:      'Lieu',
            lieuValue:      'Tunis, Tunisie',
            bioP1:          "Chokri Benomrane est professeur, mentor d'artistes et peintre tunisien. Fondateur de la peinture de l'absurde, il s'impose comme une figure majeure de l'art contemporain en Tunisie, alliant rigueur pédagogique et vision artistique radicalement personnelle.",
            bioP2:          "Son style unique combine surréalisme, expressionnisme et peinture moderne, explorant les paradoxes de l'existence à travers le contraste entre lumière et ombre, chaos et harmonie. Ses œuvres, entre abstraction et poésie visuelle, transforment l'absurde en langage pictural, révélant une esthétique originale et profondément humaine.",
            bioP3:          "À travers son parcours artistique, ses expositions et ses expérimentations, Chokri Benomrane œuvre pour la diffusion de la peinture de l'absurde en Tunisie et à l'international, affirmant sa place parmi les artistes contemporains les plus innovants et singuliers.",
            demarcheTag:    'Démarche artistique',
            demarcheTitle:  'Entre tradition et rupture',
            demarcheDesc:   "Son univers est créatif, ses expositions, ses expérimentations et ses projets offrent un accès direct à son monde artistique unique et à sa contribution au développement de l'art contemporain mondial.",
            quote:          "L'absurde n'est pas une limite — c'est le territoire où l'art commence vraiment.",
            card0tag:   'Style',
            card0title: "La peinture de l'absurde",
            card0text:  "Fondateur d'un courant singulier, Chokri Benomrane combine surréalisme, expressionnisme et peinture moderne pour explorer les paradoxes de l'existence — lumière et ombre, chaos et harmonie coexistent sur chaque toile.",
            card1tag:   'Langage pictural',
            card1title: "L'absurde en image",
            card1text:  "Ses œuvres, entre abstraction et poésie visuelle, transforment l'absurde en langage pictural. Une esthétique originale et profondément humaine qui révèle ce que les mots peinent à nommer.",
            card2tag:   'Mission',
            card2title: 'Diffusion & Transmission',
            card2text:  "Artiste, professeur et mentor, Chokri Benomrane œuvre pour la diffusion de la peinture de l'absurde en Tunisie et à l'international, affirmant sa place parmi les artistes contemporains les plus innovants.",
        },
        ateliers: {
            heroTag:      'Transmission & Partage',
            heroTitle:    'Ateliers',
            heroSub:      "Transmettre l'émotion par le geste. Rejoindre l'intimité de la création.",
            coursTag:     'Cours réguliers',
            coursTitle:   'Rejoindre un atelier',
            coursEmpty:   'Aucun cours disponible pour le moment.',
            complet:      'Complet',
            illimite:     'Places illimitées',
            surDemande:   'Sur demande',
            inscrire:     "S'inscrire",
            conseille:    'Conseillé',
            nivDebutant:  'Débutant',
            nivInter:     'Intermédiaire',
            nivAvance:    'Avancé',
            nivTous:      'Tous niveaux',
            tarif:        'Tarif',
        },
        expositions: {
            prochain:       'Prochain',
            contacter:      'Nous contacter',
            jours:          'Jours',
            heures:         'Heures',
            minutes:        'Minutes',
            historiqueTag:  'Historique',
            historiqueTitle:'Expositions passées',
            historiqueDesc: 'Un parcours à travers les galeries et foires qui ont marqué le travail de Chokri Benomrane.',
            emptyTitle:     'Aucune exposition à venir',
            emptyDesc:      'Restez informé en vous inscrivant à la newsletter ci-dessous.',
            emptyPassee:    'Aucune exposition passée enregistrée.',
            nlTag:          'Newsletter',
            nlTitle:        'Restez informé',
            nlDesc:         'Recevez les actualités et les prochaines expositions de Chokri Benomrane directement dans votre boîte mail.',
            nlPlaceholder:  'votre@email.com',
            nlSubmit:       "S'abonner",
            nlMerci:        'Merci !',
            nlMerciDesc:    'Vous recevrez nos prochaines actualités par e-mail.',
            locale:         'fr-FR',
        },
        presse: {
            heroTag:      'Revue de presse',
            heroTitle:    'Presse',
            heroDesc:     "Ce que la critique, les collectionneurs et les médias disent de l'œuvre de Chokri Benomrane.",
            navArticles:  'Articles',
            navInterviews:'Interviews & Témoignages',
            articlesTag:  'Presse écrite',
            articlesTitle:'Articles & Critiques',
            articlesEmpty:'Aucun article de presse pour le moment.',
            lireArticle:  "Lire l'article",
            interviewsTag:   'Médias',
            interviewsTitle: 'Interviews',
            interviewsEmpty: 'Aucune interview pour le moment.',
            ecouter:      'Écouter',
            voir:         'Voir',
            podcast:      'Podcast',
            video:        'Vidéo',
        },
        oeuvres: {
            title:    'Galerie',
            desc:     "Explorez l'univers visuel de Chokri Benomrane — peintures à l'huile, acryliques et dessins qui traversent le temps et la mémoire.",
            cat:      'CATÉGORIE',
            peinture: 'Peinture',
            dessin:   'Dessins',
            emptyP:   'Aucune peinture disponible.',
            emptyD:   'Aucun dessin disponible.',
            disponible:'Disponible',
            vendu:    'Vendu',
            labelDesc:    'Description',
            labelIdee:    'Idée',
            labelDispo:   'Disponibilité',
            labelAnnee:   'Année',
            labelTech:    'Technique',
            labelDim:     'Dimensions',
            reduire:      'Réduire ↑',
            afficherPlus: 'Afficher plus...',
        },
        contact: {
            title:      'Contact',
            subtitle:   'Acquisitions · Expositions · Ateliers · Commandes privées',
            formTitle:  "Formulaire d'Enquête",
            nom:        'Nom Complet',
            nomPh:      'Votre nom...',
            email:      'Email',
            tel:        'Numéro de téléphone',
            sujet:      'Sujet de la demande',
            optAcq:     "Acquisition d'œuvre",
            optExpo:    "Projet d'exposition",
            optAtel:    'Ateliers & Cours',
            optCmd:     'Commande privée',
            optPresse:  'Presse & Médias',
            message:    'Votre Message',
            messagePh:  'Comment pouvons-nous vous aider ?',
            envoyer:    'Envoyer',
            envoi:      'ENVOI...',
            direct:     'Direct',
            reseaux:    'Réseaux Sociaux',
            localisation:'Localisation',
            reponse:    'Réponse sous 48h',
            adresse:    "Atelier de l'Artiste\nCentre ville, Tunis\nTunisie",
        },
        blog: {
            tag:           'Chroniques & réflexions',
            title:         'Journal',
            desc:          "Les pensées, inspirations et réflexions de Chokri Benomrane sur l'art, la création et la vie.",
            empty:         'Aucun article pour le moment.',
            lire:          "Lire l'article",
            heroTag:       'Chroniques',
            heroTitle:     "Chroniques de l'Atelier",
            heroDesc:      'Réflexions, processus et regards sur la création picturale.',
            nlTag:         'Restez informé',
            nlTitle:       "Suivre l'atelier",
            nlDesc:        'Retrouvez les nouvelles créations et les prochaines expositions sur nos réseaux sociaux.',
            nlCta:         'Nous contacter',
            lireChronique:       'Lire la chronique →',
            retourChroniques:    '← Chroniques',
            retourToutesChroniques: '← Retour aux chroniques',
        },
    },

    en: {
        nav: {
            accueil:     'Home',
            artiste:     'The Artist',
            oeuvres:     'Gallery',
            expositions: 'Exhibitions',
            presse:      'Press',
            ateliers:    'Workshops',
            blog:        'Blogs',
            contact:     'Contact',
        },
        footer: {
            tagline:      'Tunisian painter between tradition and modernity. Oil, acrylic and pastel in the service of emotion.',
            navigation:   'Navigation',
            contact:      'Contact',
            sendMessage:  'Send a message',
            joinWorkshop: 'Join a workshop',
            rights:       'All rights reserved.',
            crafted:      'Website crafted with care',
            painter:      'Tunisian painter',
        },
        bottomNav: {
            accueil:  'Home',
            galerie:  'Gallery',
            ateliers: 'Workshops',
            contact:  'Contact',
        },
        accueil: {
            heroSub:        'Tunisian painter · founder of the painting of the absurd',
            statYears:      'Years of experience',
            statWorks:      'Works created',
            statExpo:       'Exhibitions',
            portfolioTag:   'Portfolio',
            portfolioTitle: 'Recent Works',
            portfolioCta:   'View all',
            portfolioMobile:'View all works',
            clubTag:        'Club & Transmission',
            clubTitle:      'Our workshops in pictures',
            clubCta:        'Join',
            quoteText:      'Painting is the silence of the world made visible, a confession without words, a truth without mask.',
            quoteCta:       'Discover the artist',
        },
        artiste: {
            subnavBio:      'Biography',
            subnavDemarche: 'Approach',
            bioTag:         'The Artist',
            statLabel1:     'Tunisia',
            statLabel2:     'Years of art',
            statLabel3:     'Roles',
            profLabel:      'Profession',
            profValue:      'Artist · Teacher · Mentor',
            lieuLabel:      'Location',
            lieuValue:      'Tunis, Tunisia',
            bioP1:          'Chokri Benomrane is a Tunisian painter, teacher and artist mentor. Founder of the painting of the absurd, he stands as a major figure in contemporary art in Tunisia, combining pedagogical rigor with a radically personal artistic vision.',
            bioP2:          'His unique style combines surrealism, expressionism and modern painting, exploring the paradoxes of existence through the contrast between light and shadow, chaos and harmony. His works, between abstraction and visual poetry, transform the absurd into a pictorial language, revealing an original and deeply human aesthetic.',
            bioP3:          'Through his artistic journey, exhibitions and experimentations, Chokri Benomrane works for the dissemination of the painting of the absurd in Tunisia and internationally, affirming his place among the most innovative and singular contemporary artists.',
            demarcheTag:    'Artistic approach',
            demarcheTitle:  'Between tradition and rupture',
            demarcheDesc:   'His universe is creative, his exhibitions, his experimentations and his projects offer direct access to his unique artistic world and his contribution to the development of contemporary art worldwide.',
            quote:          'The absurd is not a limit — it is the territory where art truly begins.',
            card0tag:   'Style',
            card0title: 'The painting of the absurd',
            card0text:  'Founder of a singular movement, Chokri Benomrane combines surrealism, expressionism and modern painting to explore the paradoxes of existence — light and shadow, chaos and harmony coexist on each canvas.',
            card1tag:   'Pictorial language',
            card1title: 'The absurd in images',
            card1text:  'His works, between abstraction and visual poetry, transform the absurd into a pictorial language. An original and deeply human aesthetic that reveals what words struggle to name.',
            card2tag:   'Mission',
            card2title: 'Dissemination & Transmission',
            card2text:  'Artist, professor and mentor, Chokri Benomrane works for the dissemination of the painting of the absurd in Tunisia and internationally, affirming his place among the most innovative contemporary artists.',
        },
        ateliers: {
            heroTag:      'Transmission & Sharing',
            heroTitle:    'Workshops',
            heroSub:      'Transmitting emotion through gesture. Joining the intimacy of creation.',
            coursTag:     'Regular courses',
            coursTitle:   'Join a workshop',
            coursEmpty:   'No courses available at the moment.',
            complet:      'Full',
            illimite:     'Unlimited spots',
            surDemande:   'On request',
            inscrire:     'Register',
            conseille:    'Recommended',
            nivDebutant:  'Beginner',
            nivInter:     'Intermediate',
            nivAvance:    'Advanced',
            nivTous:      'All levels',
            tarif:        'Price',
        },
        expositions: {
            prochain:       'Next',
            contacter:      'Contact us',
            jours:          'Days',
            heures:         'Hours',
            minutes:        'Minutes',
            historiqueTag:  'History',
            historiqueTitle:'Past exhibitions',
            historiqueDesc: 'A journey through the galleries and fairs that marked the work of Chokri Benomrane.',
            emptyTitle:     'No upcoming exhibition',
            emptyDesc:      'Stay informed by subscribing to the newsletter below.',
            emptyPassee:    'No past exhibitions recorded.',
            nlTag:          'Newsletter',
            nlTitle:        'Stay informed',
            nlDesc:         'Receive news and upcoming exhibitions by Chokri Benomrane directly in your inbox.',
            nlPlaceholder:  'your@email.com',
            nlSubmit:       'Subscribe',
            nlMerci:        'Thank you!',
            nlMerciDesc:    'You will receive our upcoming news by email.',
            locale:         'en-US',
        },
        presse: {
            heroTag:      'Press review',
            heroTitle:    'Press',
            heroDesc:     'What critics, collectors and media say about the work of Chokri Benomrane.',
            navArticles:  'Articles',
            navInterviews:'Interviews & Reviews',
            articlesTag:  'Written press',
            articlesTitle:'Articles & Reviews',
            articlesEmpty:'No press articles at the moment.',
            lireArticle:  'Read the article',
            interviewsTag:   'Media',
            interviewsTitle: 'Interviews',
            interviewsEmpty: 'No interviews at the moment.',
            ecouter:      'Listen',
            voir:         'Watch',
            podcast:      'Podcast',
            video:        'Video',
        },
        oeuvres: {
            title:    'Gallery',
            desc:     'Explore the visual universe of Chokri Benomrane — oil paintings, acrylics and drawings that cross time and memory.',
            cat:      'CATEGORY',
            peinture: 'Paintings',
            dessin:   'Drawings',
            emptyP:   'No paintings available.',
            emptyD:   'No drawings available.',
            disponible:'Available',
            vendu:    'Sold',
            labelDesc:    'Description',
            labelIdee:    'Concept',
            labelDispo:   'Availability',
            labelAnnee:   'Year',
            labelTech:    'Technique',
            labelDim:     'Dimensions',
            reduire:      'Collapse ↑',
            afficherPlus: 'Show more...',
        },
        contact: {
            title:      'Contact',
            subtitle:   'Acquisitions · Exhibitions · Workshops · Private commissions',
            formTitle:  'Enquiry Form',
            nom:        'Full Name',
            nomPh:      'Your name...',
            email:      'Email',
            tel:        'Phone number',
            sujet:      'Subject of request',
            optAcq:     'Artwork acquisition',
            optExpo:    'Exhibition project',
            optAtel:    'Workshops & Courses',
            optCmd:     'Private commission',
            optPresse:  'Press & Media',
            message:    'Your Message',
            messagePh:  'How can we help you?',
            envoyer:    'Send',
            envoi:      'SENDING...',
            direct:     'Direct',
            reseaux:    'Social Networks',
            localisation:'Location',
            reponse:    'Response within 48h',
            adresse:    "Artist's Studio\nCity centre, Tunis\nTunisia",
        },
        blog: {
            tag:           'Chronicles & reflections',
            title:         'Journal',
            desc:          'The thoughts, inspirations and reflections of Chokri Benomrane on art, creation and life.',
            empty:         'No articles at the moment.',
            lire:          'Read the article',
            heroTag:       'Chronicles',
            heroTitle:     'Studio Chronicles',
            heroDesc:      'Reflections, process and views on pictorial creation.',
            nlTag:         'Stay informed',
            nlTitle:       'Follow the studio',
            nlDesc:        'Find new creations and upcoming exhibitions on our social media.',
            nlCta:         'Contact us',
            lireChronique:          'Read the chronicle →',
            retourChroniques:       '← Chronicles',
            retourToutesChroniques: '← Back to chronicles',
        },
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => {
        try { return localStorage.getItem('lang') || 'fr'; }
        catch { return 'fr'; }
    });

    useEffect(() => {
        try { localStorage.setItem('lang', lang); } catch {}
    }, [lang]);

    const toggle = () => setLang(l => l === 'fr' ? 'en' : 'fr');
    const t = (section, key) => T[lang]?.[section]?.[key] ?? key;

    return (
        <LanguageContext.Provider value={{ lang, toggle, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
